// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiHC0LNNdui_C3R4VI1Xhz2yN4toAdmwg',
    appId: '1:319044794629:web:98d01e97adafb8b4069f6c',
    messagingSenderId: '319044794629',
    projectId: 'hostepil1200',
    authDomain: 'hostepil1200.firebaseapp.com',
    storageBucket: 'hostepil1200.appspot.com',
    measurementId: 'G-D73CXRVN1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQokPj8MHdsi-Tai6Zx2vC3b_hkpHNbo',
    appId: '1:319044794629:android:eddd4da9903e72f8069f6c',
    messagingSenderId: '319044794629',
    projectId: 'hostepil1200',
    storageBucket: 'hostepil1200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd35Z9DMEVo7Y-S-SZUOk3hpi-JyjtCGA',
    appId: '1:319044794629:ios:f8b77a2f4c22cd83069f6c',
    messagingSenderId: '319044794629',
    projectId: 'hostepil1200',
    storageBucket: 'hostepil1200.appspot.com',
    androidClientId: '319044794629-039u4c9ie9l4doqmn7ocj51d7kjb44n6.apps.googleusercontent.com',
    iosClientId: '319044794629-73dps1itf1moj9726m1t7js03cjr4cb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostepil1200',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd35Z9DMEVo7Y-S-SZUOk3hpi-JyjtCGA',
    appId: '1:319044794629:ios:f8b77a2f4c22cd83069f6c',
    messagingSenderId: '319044794629',
    projectId: 'hostepil1200',
    storageBucket: 'hostepil1200.appspot.com',
    androidClientId: '319044794629-039u4c9ie9l4doqmn7ocj51d7kjb44n6.apps.googleusercontent.com',
    iosClientId: '319044794629-73dps1itf1moj9726m1t7js03cjr4cb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostepil1200',
  );
}
